### ISSUE TITLE
Configuration error

### ISSUE THREAD

**Issue by dmbuchta** [AdolfVonKleist/Phonetisaurus#10]
I configured openfst like so:
`sudo ./configure --enable-static --enable-shared --enable-far \ --enable-lookahead-fsts --enable-const-fsts --enable-pdt \ --enable-ngram-fsts --enable-linear-fsts CC=gcc-4.9
`
and then installed it. But I still get a configuration error when trying to configure Phonetisaurs:
`configure: error: Can't find one or more extensions.  OpenFst should                     have been configured with the following flags:                          --enable-static --enable-shared --enable-far --enable-lookahead-fsts        --enable-const-fsts --enable-pdt --enable-ngram-fsts --enable-linear-fsts`

**Comment by dthomas888** [comment]
I have the same problem. its fails the configuration check because libfstlinearscript.so is not generated in /usr/local/lib/fst all other extensions have been created.

**Comment by PaulPoveda** [comment]
Hello everyone,

I get the same error as dmbuchta and I had installed OpenFst 1.4 and I got the same error : 

`Found OpenFst headers.
configure: WARNING: OpenFst headers do not appear to be patched.  Did you apply the Kaldi OpenFst patch?  Might be problematic when using with Kaldi.
configure: creating ./config.status
config.status: creating Makefile
`

Any solution for this ?

**Comment by imrehg** [comment]
Regarding the original issue, looks like those files were searched for e.g. in `/usr/local/lib/fst`, while in fact they live in `/usr/local/lib/` directly (at least it's there on my Debian system). My solution was to symlink them to be also available in the `fst` subdirectory, i.e.:
```
# cd /usr/local/lib
# for f in libfst*; do ln -s "../$f" "fst/$f"; done
```
After this the configuration succeeds.

**Comment by brownedon** [comment]
Thanks imrehg, the links work for me on a Raspberry PI 3.  I had trouble with the script above, so I echoed it to a file, then edited the link commands, removing the ../ from each line, ending up with:
Example line:
sudo ln -s /usr/local/lib/libfstlookahead.a /usr/local/lib/fst/libfstlookahead.a

**Comment by ProgramadorDeValor** [comment]
Hi, I got the same error and tried exactly what @imrehg suggested, but I had no success at all :/ I'm also using raspberry pi 3. 

I tried to force the command ./configure --with-openfst-includes=/usr/local/include --with-openfst-libs=/usr/local/lib/ 

My last try was with openfst 1.4.2, but before, i tried with 1.5.3 and the same message appears. 

Any light would be apreciated .  Thank you.

**Comment by jedediahfrey** [comment]
The problem comes with these 2 lines:

```
            -a -e "$with_openfst_libs/fst/libfstlookahead.so" \
            -a -e "$with_openfst_libs/fst/libfstlinearscript.so"; then :
```

It doesn't look like those are installed on later versions.

I tried cutting it out. It made the make file but the make failed.

**Comment by AdolfVonKleist** [comment]
These two lines are removed now, as they are not actual requirements for the phonetisaurus - they are used with other programs that integrate with OpenFst for various purposes.  I believe this should be resolved in the [kaldi](https://github.com/AdolfVonKleist/Phonetisaurus/tree/kaldi) tag, and in [master](https://github.com/AdolfVonKleist/Phonetisaurus/tree/master) at this point, at least for OpenFst v1.6.x.

We can reopen if there is still something pending.

**Comment by rmachad5** [comment]
@dmbuchta how exactly did you fix this issue? I'. trying to install openfst 1.4.1 and getting same issue and have tried the numerous different configure combos and can't seem to find an answer.

**Comment by Nimitz14** [comment]
Still a problem.

**Comment by AdolfVonKleist** [comment]
Still a problem with 1.6.x or still a problem with 1.4.x?  There are some breaking changes in the transition.  I can probably give some hints/feedback to specifics on 1.4.x but I'd rather not try to simultaneously support it.
