### ISSUE TITLE
 error: expected ')' before 'it1' "IN PHONETISAURUS"

### ISSUE THREAD

**Issue by theja0473** [AdolfVonKleist/Phonetisaurus#13]
![phonetisarus_error_2](https://cloud.githubusercontent.com/assets/15976291/15210916/1782180c-1856-11e6-9ea9-ee3f46b62d8f.JPG)

I am facing the above error please give me solution if any body knows.

**Comment by AdolfVonKleist** [comment]
I believe this is related to an interaction with certain versions of OpenFst.  You probably need to restart with master (which is now moving to 1.6.1), or the 1.5.3 branch if you are using 1.5x.
