### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by phineas0fog** [AdolfVonKleist/Phonetisaurus#19]
Hello :)
I'm trying to install "jasper-stt-pocketsphinx", and need phonetisaurus, but I've an error when I try to build the packet from AUR. I use ManjaroLinux with 4.11 kernel.
Here is the full output with the errors at the end... https://gist.github.com/phineas0fog/6078add416575eeedcb93851e9241fc8
Thanks for help :D

**Comment by AdolfVonKleist** [comment]
Can you share the link that it is using to download ```phonetisaurus-0.8a.tgz```?  I don't have anything to do with Jasper, but I'll take a look if you can share me the link [I'm assuming it is from googlecode, but just in case...]

**Comment by AdolfVonKleist** [comment]
I'm closing this due to lack of response on the issue.
