### ISSUE TITLE
ReadMe has incorrect configure step for openfst.

### ISSUE THREAD

**Issue by taji** [AdolfVonKleist/Phonetisaurus#2]
This configure command 

<pre>
./configure --enable-compact-fsts --enable-const-fsts \
    --enable-far --enable-lookahead-fsts --enable-pdt --ngram-fsts
</pre>

Should be:

<pre>
./configure --enable-compact-fsts --enable-const-fsts \
    --enable-far --enable-lookahead-fsts --enable-pdt --<b>enable</b>-ngram-fsts
</pre>

**Comment by taji** [comment]
And just to be thorough on the entire build and test process as described in the ReadMe:  (installing under Ubuntu):

1. Make sure you have the following installed via apt-get: build-essential, python, python-dev, python-setuptools, python-twisted.
2. Make sure your LD_LIBRARY_PATH environment variable is set to : /usr/local/lib.

**Comment by taji** [comment]
Finally one more thing, this command:

    phonetisaurus-arpa2wfst-omega --lm=test.arpa --ofile=test.fst

returns a 1 exit code (rather than a 0).  Should it?

I'm building a Docker container and adding this line as a RUN command in my Dockerfile causes the the Docker build to break.  Right now I'm working around the issue by invoking the command like this:

<pre>
phonetisaurus-arpa2wfst-omega --lm=test.arpa --ofile=test.fst <b>|| true</b>
</pre>

BTW, love the twisted service implementation. Makes rpc a snap :-)

**Comment by theja0473** [comment]
It is not working for my RPI.
![errorcapture](https://cloud.githubusercontent.com/assets/15976291/14982257/c55ca1b4-1152-11e6-9565-a7cd64a18ae3.JPG)

**Comment by theja0473** [comment]
could you please advice another ./configure command

**Comment by theja0473** [comment]
I am using bellow g++ version.
![g version](https://cloud.githubusercontent.com/assets/15976291/14982318/2d439346-1153-11e6-955c-0d04a5e6714d.JPG)

**Comment by AlJohri** [comment]
@theja0473 what are you doing?? why are you commenting on 3 different unrelated issues?

**Comment by dmbuchta** [comment]
I'm still having a configuration error with openfst using the updated ReadMe. Please see #10, any advice would be appreciated.

**Comment by AdolfVonKleist** [comment]
This should now be resolved thanks to @AlJohri  pull request.
