### ISSUE TITLE
Installation failed; lib/libphonetisaurus.so missing

### ISSUE THREAD

**Issue by egazetic1** [AdolfVonKleist/Phonetisaurus#21]
I tried to install Phonetisaurus a few times today, but I always get the same result. 

When I run "**./configure**" I get at the end of configure:
Set default OpenFst libs: /usr/local/lib
Found basic OpenFst installation.
Found all required OpenFst extensions.
Set default installation directory: /usr/local/bin
Set default libraries installtion directory: /usr/local/lib
Set default OpenFst includes: /usr/local/include
Found OpenFst headers.
configure: WARNING: OpenFst headers do not appear to be patched.  Did you apply the Kaldi OpenFst patch?  Might be problematic when using with Kaldi.
configure: creating ./config.status
config.status: creating Makefile
mv: cannot move 'config.log' to '.autoconf/config.log': Text file busy

with "**make**" I get at the end of the build:
make: warning:  Clock skew detected.  Your build may be incomplete.

and then with "**sudo make install**" I get the next output: 
make: Warning: File 'Makefile' has modification time 36133 s in the future
install -D -m 755 bin/phonetisaurus-align /usr/local/bin/phonetisaurus-align
install -D -m 755 bin/phonetisaurus-arpa2wfst /usr/local/bin/phonetisaurus-arpa2wfst
install -D -m 755 bin/phonetisaurus-g2prnn /usr/local/bin/phonetisaurus-g2prnn
install -D -m 755 bin/phonetisaurus-g2pfst /usr/local/bin/phonetisaurus-g2pfst
install -D -m 755 bin/rnnlm /usr/local/bin/rnnlm
install -c lib/libphonetisaurus.so /usr/local/lib/
install: cannot stat 'lib/libphonetisaurus.so': No such file or directory
Makefile:156: recipe for target 'install' failed
make: *** [install] Error 1

I searched all the directories after libphonetisaurus.so. But I couldn't find it anywhere. 

Any tip would be helpful :)

**Comment by AdolfVonKleist** [comment]
Can you tell me what OS you are running on?  I have not seen the 'config' error before.

Also what happens if you try running:
```
make phonetisaurus-binding
```
and then ```make install```?

We should probably include the library build in the general, or remove it from install.

**Comment by AdolfVonKleist** [comment]
I've updated the ```Makefile``` to remove the bindings library from the ```install``` block.  This should resolve this issue.  I don't know about the ```config.log``` issue or the clock issue - those appear to be related to your distro and/or system configuration [VM maybe?].
