### ISSUE TITLE
script/phoneticize.py arg parsing error

### ISSUE THREAD

**Issue by jcbloch** [AdolfVonKleist/Phonetisaurus#26]
script fails with

`Traceback (most recent call last):
  File ".phoneticize.py", line 60, in <module>
    action="store_true")
  File "/usr/lib/python2.7/argparse.py", line 1294, in add_argument
    action = action_class(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'type'`

Python 2.7.9 

removing the `type=bool` fixes it.

What python env's are supported?

**Comment by AdolfVonKleist** [comment]
Thanks, this looks to be related to sloppy misuse of ```argparse```.  In theory 2.x should work, although anything less than 2.7 requires a ```pip install argparse``` or equivalent.  [#8a34e63](https://github.com/AdolfVonKleist/Phonetisaurus/commit/8a34e63701505ee2af9e21b7f66c9100811686f0) applies your suggestion.
