### ISSUE TITLE
What happened to this project?

### ISSUE THREAD

**Issue by modsognir** [AdolfVonKleist/Phonetisaurus#3]
Why is it all gone?

**Comment by Holzhaus** [comment]
I'm wondering, too.

You can still clone the repo and `git reset --hard HEAD^` though.

**Comment by allomov** [comment]
I am also interested in this project. How can I access the repo?

**Comment by Holzhaus** [comment]
```
$ git clone https://github.com/AdolfVonKleist/Phonetisaurus.git
Cloning into 'Phonetisaurus'...
remote: Counting objects: 168, done.
remote: Total 168 (delta 0), reused 0 (delta 0), pack-reused 168
Receiving objects: 100% (168/168), 330.83 KiB | 0 bytes/s, done.
Resolving deltas: 100% (39/39), done.
Checking connectivity... done.

$ cd Phonetisaurus 
$ git checkout HEAD^
Note: checking out 'HEAD^'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at d81b8e3... Fix data-length handling for persistant client. Why is the persistant client *slower* than the rebuild?  Fastest is still batch-mode.

$ ls -l
total 8
-rw-r--r-- 1 jan jan 3997 Sep  2 15:54 README.md
drwxr-xr-x 2 jan jan   60 Sep  2 15:54 phonetisaurus
drwxr-xr-x 2 jan jan   60 Sep  2 15:54 rnnlm
drwxr-xr-x 2 jan jan  240 Sep  2 15:54 script
-rw-r--r-- 1 jan jan 1001 Sep  2 15:54 setup.py
drwxr-xr-x 5 jan jan  480 Sep  2 15:54 src
drwxr-xr-x 2 jan jan  160 Sep  2 15:54 tests
```

**Comment by AdolfVonKleist** [comment]
i'm still actively working on this project.  i'm trying to reboot it, but have been a bit swamped at work lately.

**Comment by modsognir** [comment]
No worries, what was the reason the code tree was deleted?

**Comment by JosefNovak** [comment]
it is not actually deleted - the entire history is still there.  i had planned on migrating all the changes the over the next couple days after I did this, but a bunch of other work appeared unexpectedly and this got pushed to the bottom of the stack.   i also honestly did not realize that there was a decent number of people actually using it...

the intended plan is to merge the RNN and additional alignment work I've done, which is currently in separate repos, and to provide some different options for compilation which enable better compatibility with Kaldi, and a choice regarding bindings and shared-library construction.  

this seemed like the 'right' way to do it at the time. finally, for some reason the notifications for this project were for some reason going to a different email that i rarely check, so i didn't even notice this until last weekend.

the stable legacy builds, experiments packages and googlecode documentation are also still available as downloads on the original site.  i did manage to do that before googlecode shut down:

https://code.google.com/p/phonetisaurus/

**Comment by modsognir** [comment]
Sounds like a good future. I was just a little concerned as it looked like
it had been hacked!

For reference, the open source project Jasper uses this, and as I was
trying to install that I found I had to compile from source because of
issues on my system beyond my comprehension.

https://jasperproject.github.io/

**Comment by AdolfVonKleist** [comment]
Thanks!
