### ISSUE TITLE
evaluatation

### ISSUE THREAD

**Issue by matin-amiri** [AdolfVonKleist/Phonetisaurus#40]
hi
is there any command to use check-nbest-wer.py for evaluation and generating a result file?

**Comment by AdolfVonKleist** [comment]
Hi, It is hard-coded to the g014b2b example regression.  You could modify it to use some other test set that you have.  It should not be too much work to swap it.  In general the nbest WER eval for g2p is just generating an nbest list and comparing the reference(s) against your hypotheses and looking for a match.  Note this is different from PER (Phoneme Error Rate).

**Comment by matin-amiri** [comment]
thanks for your explaination
but the problem is when I run check-nbest-wer.py through python2 <check-nbest-wer.py>.py command 
 although corpus, fst, arpa and hypo files are built but it dosen't build any result file and do not print these lines of the source code 
 print "Corr: {0}, Err: {1}, WACC: {2:0.2f}%, WER: {3:0.2f}%".format (
        corr,
        total - corr,
        corr / total * 100,
        (1.0 - (corr / total)) * 100
    )
and it ends by saving arpa and converting .how can i fix it?

**Comment by matin-amiri** [comment]
thank u for your explanation
but the problem is when I run check-nbest-wer.py through python2 <check-nbest-wer.py>.py although all the corpus, fst, arpa and hyp files are built but it dosn't build any result file and do not show me any WER  and these lines of source codes:
 print "Corr: {0}, Err: {1}, WACC: {2:0.2f}%, WER: {3:0.2f}%".format (
        corr,
        total - corr,
        corr / total * 100,
        (1.0 - (corr / total)) * 100
    )

how can i fix that? and see  the WER?

**Comment by AdolfVonKleist** [comment]
Hi, I just checked out the latest master, recompiled, and reran `check-nbest-wer.py` from scratch.  This is the log output I get [minus a couple of redundant iteration lines]:
```
/tmp/Phonetisaurus/test$ ./check-nbest-wer.py --prefix g014b2b
Standard alignment
GitRevision: kaldi-6-g64719c
Loading input file: g014b2b/g014b2b.train
...
Starting EM...
Finished first iter...
...
Last iteration:
Alignment with support for growing
GitRevision: kaldi-6-g64719c
Loading input file: g014b2b/g014b2b.train
...
Starting EM...
Finished first iter...
...
Last iteration:

Training standard ARPA
0.001   Loading corpus g014b2b/g014b2b.corpus...
...
0.497   Estimating full n-gram model...
0.515   Saving LM to g014b2b/g014b2b.o8.arpa...
Training grow-supported ARPA
0.001   Loading corpus g014b2b/g014b2b.grow.corpus...
...
0.529   Saving LM to g014b2b/g014b2b.grow.o8.arpa...

Converting stanard model to Fst
GitRevision: kaldi-6-g64719c
Initializing...
Converting...
Converting grow-reported stanard model to Fst
GitRevision: kaldi-6-g64719c
Initializing...
Converting...

Testing 5-best standard
GitRevision: kaldi-6-g64719c
Testing 5-best grow-supported standard
GitRevision: kaldi-6-g64719c
Corr: 11229.0, Err: 771.0, WACC: 93.58%, WER: 6.43%
Corr: 11232.0, Err: 768.0, WACC: 93.60%, WER: 6.40%
```

Note again: This _hardcoded_ to the `g014b2b` reference corpus.  If you want to adapt it to another corpus/test set, you must modify all references in the script to match your corpus/test set file names, and provide your own references file to compare against.  You also need to make sure that all the binaries being called by the script are available via your `$PATH`.
