### ISSUE TITLE
Failure transitions

### ISSUE THREAD

**Issue by jpetso** [AdolfVonKleist/Phonetisaurus#41]
In [the Phonetisaurus failure transitions paper](http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.640.5602&rep=rep1&type=pdf), three variants are described for handling backoff transitions, representing different speed vs. memory tradeoffs. I also found that the [is2013-conversion.tgz](https://code.google.com/archive/p/phonetisaurus/downloads) tarball contains a PhonetisaurusOmega class, which on first glance appears to implement the described conversion(s).

I tried Phonetisaurus with nbest > 1, realized it's much slower than with default nbest == 1, and didn't see any choices or comments related to these failure transitions in the repository here. Am I running into that same problem? Is this something that should still be added? Or was it not production ready? Or am I missing something?

Thanks in advance for a reply and also for this awesome piece of software!

**Comment by AdolfVonKleist** [comment]
@jpetso thanks for your message.  As you noted, the algorithms in the failure transitions paper are implemented in the tarball [along with the evaluation scripts].   The current master is largely a rewrite taking only the most generally useful functionality, and does not include currently reimplement these.  The general speed of the nbest may be quite heavily impacted by also by the search parameters that you supply, as well as the structure of the input model, but it will typically be slower than one best.  I can probably help you tune it a bit with more detail.

**Comment by jpetso** [comment]
Thanks, I'll check the actual code and see if there's an easy way for me to try this without taking much of your time. In terms of search parameters, I've found that the combination of nbest and beam size makes the biggest impact. Either way, I still have to learn more about how this all works. Thanks to your papers being actually readable by a non-academic software engineer like me, there's a chance I'll figure it out eventually :)

**Comment by AdolfVonKleist** [comment]
The tarballed version should allow you to select your preferred failure transition approach.
