### ISSUE TITLE
Segmentation fault (core dumped) Error

### ISSUE THREAD

**Issue by matin-amiri** [AdolfVonKleist/Phonetisaurus#42]
hi
I trained  Rnn-LM once with cmudict.corpus and  it gives me a test.rnn file as output then I tride to run g2prnn through this command"Phonetisaurus$ phonetisaurus-g2prnn --rnnlm=test.rnnlm --word="test" \ --nbest=3"
but I get this error:

Segmentation fault (core dumped) 

for second time I trained Rnn-LM with  cmudict.formated.txt and tried to run g2prnn but i got this erroe again.
what should i do to debug this error?

**Comment by AdolfVonKleist** [comment]
I separated this out a long time ago, and started to work on a new version locally.  You can access the old version here: https://github.com/AdolfVonKleist/RnnLMG2P  I guess it may make sense to fold this back in here though as it is unlikely right now that I'll have time to continue the previously planned work in the near future.
