### ISSUE TITLE
No module Phonetisaurus found

### ISSUE THREAD

**Issue by nishant260190** [AdolfVonKleist/Phonetisaurus#43]
I am new to this and following steps given in READMD.md 

Everythig is ruinning fine till the point I run command
./phoneticize.py -m ~/example/cmudict.o8.fst -w testing

And while running this command I got the error : No module Phonetisaurus found
I am trying to install using command 'pip3 install Phonetisaurus' but no such library exists in python.
So please suggest something what should I do next ?

**Comment by zgoda** [comment]
Phonetisaurus.so is missing from package. I guess `setup.py` produces wrong package manifest, this file is missing also from source distribution (`sdist`) and from wheel (`bdist_wheel`).

**Comment by AdolfVonKleist** [comment]
Hi,
Did you use the instructions for the python bindings?
You must the compilation directions for the bindings:
-------------------
$ git clone https://github.com/AdolfVonKleist/Phonetisaurus.git
$ cd Phonetisaurus
$ sudo pip install pybindgen
*$ ./configure --enable-python*
$ make
$ sudo make install
$ cd python


*$ cp ../.libs/Phonetisaurus.so .$ sudo python setup.py install$ cd*
----------------

or else the .so file will not be built.  You must also manually move it.

from what you wrote it looks like got the c++ tools compiled, so my guess
is you used those directions rather than the python bindings ones.


2019年9月11日(水) 14:42 Jarek Zgoda <notifications@github.com>:

**Comment by zgoda** [comment]
Yes, exactly as in README.

Content of phonetisaurus.egg-info/SOURCES.txt:

```
setup.py
phonetisaurus/__init__.py
phonetisaurus.egg-info/PKG-INFO
phonetisaurus.egg-info/SOURCES.txt
phonetisaurus.egg-info/dependency_links.txt
phonetisaurus.egg-info/not-zip-safe
phonetisaurus.egg-info/requires.txt
```

(this is what goes to source distribution)

Content of RECORD file in wheel package:

```
phonetisaurus/__init__.py,sha256=XLytcL9WChEC1YoZS73TPBgB1zvAY8k601zpdX1-HOs,63
phonetisaurus-0.3.dist-info/METADATA,sha256=NLcPNBonaQ7VDfihYokuh1UBO3jDYQdQYC5a6pOpviw,314
phonetisaurus-0.3.dist-info/WHEEL,sha256=S8S5VL-stOTSZDYxHyf0KP7eds0J72qrK0Evu3TfyAY,92
phonetisaurus-0.3.dist-info/top_level.txt,sha256=8Y-KQPKC0qU6_IwmWng517W4r-4sxINmdZZD-0-eo40,14
phonetisaurus-0.3.dist-info/RECORD,,
```

(this is what is copied to `build/bdist` and then goes to binary package)

Both source and binary packages are missing `Phonetisaurus.so` file. I think it should go not to the top level dir but to `phonetisaurus/` subdirectory.

**Comment by zgoda** [comment]
Okay, `sdist` will not copy this file to distribution but with my above workaround I now have proper installation and it is included in wheel package.

**Comment by AdolfVonKleist** [comment]
Interesting, it's worked like that first commit, but you are definitely right.  For the OpenFst 1.7.3 update I'm doing something like this right now, and I did encounter similar issues with python3.6:
```
#!/usr/bin/python3
from setuptools import setup
import glob
#from distutils.core import setup

#Install phonetisaurus
setup (
    name         = 'phonetisaurus',
    version      = '0.3',
    description  = 'Phonetisaurus G2P python package (OpenFst-1.7.3)',
    url          = 'http://code.google.com/p/phonetisaurus',
    author       = 'Josef Novak',
    author_email = 'josef.robert.novak@gmail.com',
    license      = 'BSD',
    packages     = ['phonetisaurus'],
    data_files   = [
        ('/usr/local/lib/python3.6/dist-packages',
         glob.glob ('phonetisaurus/Phonetisaurus.so'))
    ],
    classifiers=[
        'Development Status :: 1 - Alpha',
        'Intended Audience :: Developers',
        'Topic :: Software Development :: STT, NLP',
        'License :: PRIVATE',
        'Programming Language :: Python :: 3.7'
    ],
    python_requires='>=3.7',
    install_requires = [],
    entry_points = {
        'console_scripts': [
            'g2p_server=phonetisaurus:g2p_server'
        ]
    },
    zip_safe = False
)```

this is working now [at least for my test docker and dpkg builds] but it's probably got plenty of issues.  If you have any suggestions or want to create a pull request, all would be welcome.
