### ISSUE TITLE
Alignment failed.

### ISSUE THREAD

**Issue by giampierosalvi** [AdolfVonKleist/Phonetisaurus#44]
Hi,
I was trying to run Phonetisaurus with a relatively large dictionary (over 800.000 entries) and I got "Alignment failed. Exiting." after a while the script was running. I clearly ran over the 16GB of RAM in my machine because the computer has become unresponsive before failing. However, I would like to be sure that this is a memory issue and not something wrong with the format of my dictionary. Is there a way to get more debug information from the program? What is the largest dictionary you have tested the program with? With how much RAM?

I ran the following command
phonetisaurus-train --lexicon full.dic --seq2_del
on Ubuntu 18.04 with python 3.5.5 (Anaconda). I had to do some minor modifications to the script to run with python 3, but nothing that should cause a change in behaviour.

Thank you!
Giampiero

**Comment by AdolfVonKleist** [comment]
Hi, thanks for this.  The largest dictionary I have personally used is 1.8M entries.  It also required a significant amount of RAM.  

The RAM usage will be affected by both the average length of the entries, and the total number.  This implementation keeps the complete collection of FSTs in memory during the alignment process, which is super simple, but can make it a RAM hog pretty quick.

If you want, you can try the on-disk version of the aligner; it is slower but won't suffer from this drawback:
 - https://github.com/AdolfVonKleist/AltFstAligner

and I toyed with it for exactly this reason.  You can also use M2MAligner (https://code.google.com/archive/p/m2m-aligner/); no FST representation [which is incidental anyway], but the phonetisaurus aligner is based on M2M; you would just need to reformat the final text output before feeding it to the LM training phase.

**Comment by giampierosalvi** [comment]
Thanks, I have tried the current version on a bigger machine and it worked. The process took around 15GB of RAM, so I was just short of RAM on my machine.

Thank you for the quick response and for the information.

**Comment by AdolfVonKleist** [comment]
Glad you got it to work.  Cheers.
