### ISSUE TITLE
Python3 support (with workaround)

### ISSUE THREAD

**Issue by ajanin** [AdolfVonKleist/Phonetisaurus#46]
I had a bit of a problem getting Phonetisaurus to work with python3. The only problem seems to be an out-of-date copy of `pybindgen`. My solution:

```
git clone https://github.com/AdolfVonKleist/Phonetisaurus.git
cd Phonetisaurus
rm -rf python/pybindgen
pip3 install --user pybindgen
PYTHON=python3 ./configure [...]
```

I'm testing a branch that removes the local copy of `pybindgen` and documents installing `pybindgen` and python2 vs. python3 changes.

**Comment by AdolfVonKleist** [comment]
Thanks this works, and is now added to the docs.  I also used this bit in the draft update for openfst 1.7.3 [https://github.com/AdolfVonKleist/Phonetisaurus/tree/openfst173].  I'm closing this.
