### ISSUE TITLE
i have no idea with is error ?!

### ISSUE THREAD

**Issue by maya413** [AdolfVonKleist/Phonetisaurus#49]
$ phonetisaurus-g2pfst  --model=F:\\Dataset\\mfa\\mandarin_pinyin_g2p_model\\CH\\model.fst --wordlist=C:\\Users\\Administrator\\Documents\\MFA\\G2P\\G2P\\mandarin_pinyin_g2p\\words.txt
GitRevision: kaldi-12-g17d4df
' not found in input symbols table.
Mapping to null...
an1quan29.46396 a1 n q va2 n
' not found in input symbols table.
Mapping to null...
ba1shi2n23.19154b a1 sh ii2 n ia2 n d ai4
' not found in input symbols table.
Mapping to null...
bao1luo130.255anb ao1 l uo1 ua4 n x ia4 ng
' not found in input symbols table.
Mapping to null...
bao3zhen10.7499 b ao3 zh e4 ng
' not found in input symbols table.
Mapping to null...
bi4xu1  12.0275 b i4 x v1
' not found in input symbols table.
Mapping to null...
bu4     9.92609 b u4
' not found in input symbols table.
Mapping to null...
chao1   9.00259 ch ao1
' not found in input symbols table.
Mapping to null...
cheng1  9.67122 ch e1 ng
' not found in input symbols table.
Mapping to null...
chu1fa1 11.2742 ch u1 f a1
' not found in input symbols table.
Mapping to null...
chu1yu2 11.6118 ch u1 v2
' not found in input symbols table.
Mapping to null...
cong2   9.09867 c o2 ng
' not found in input symbols table.
Mapping to null...
da4     9.96387 d a4
' not found in input symbols table.
Mapping to null...
da4xing212.2178 d a4 x i2 ng
' not found in input symbols table.
Mapping to null...
dao4    8.98174 d ao4
' not found in input symbols table.
Mapping to null...
de5     11.0093 d e5
' not found in input symbols table.
Mapping to null...
duo1tou212.1811 d uo1 t ou2
' not found in input symbols table.
Mapping to null...
er2jin1 13.6158 e2 r j i1 n
' not found in input symbols table.
Mapping to null...
er3sai1 17.3558 e3 r s ai1
' not found in input symbols table.
Mapping to null...
geng1niu12.8542 g e1 ng n iu2
' not found in input symbols table.
Mapping to null...
gou1si1 15.8097 g ou1 s ii1
' not found in input symbols table.
Mapping to null...
guo2wu4y12.3834 g uo2 u4 va4 n
' not found in input symbols table.
Mapping to null...
he2     9.22432 h e2
' not found in input symbols table.
Mapping to null...
he2di4  11.3964 h e2 d i4
' not found in input symbols table.
Mapping to null...
hu4     9.02583 h u4
' not found in input symbols table.
Mapping to null...
jian3ce412.0665 j ia3 n c e4
' not found in input symbols table.
Mapping to null...
jiang1  8.94055 j ia1 ng
' not found in input symbols table.
Mapping to null...
jiang3qi12.4117 j ia3 ng q iu2
' not found in input symbols table.
Mapping to null...
jin3    8.94537 j i3 n
' not found in input symbols table.
Mapping to null...
jing1yin10.0806 j i1 ng i2 ng
' not found in input symbols table.
Mapping to null...
jing3wei11.2351 j i3 ng uei4
' not found in input symbols table.
Mapping to null...
jue2dui423.96912j ve2 d uei4 a1 n q va2 n
' not found in input symbols table.
Mapping to null...
ka1bu4er13.2322 k a1 b u4 e3 r
' not found in input symbols table.
Mapping to null...
kao3lv4 10.9573 k ao3 l v4
' not found in input symbols table.
Mapping to null...
ke3     9.88771 k e3
' not found in input symbols table.
Mapping to null...
ke3yi3  11.2246 k e3 i3
' not found in input symbols table.
Mapping to null...
ke3yi3sh21.4234 k e3 i3 sh uo1
' not found in input symbols table.
Mapping to null...
li4sheng11.2368 l i4 sh e1 ng
' not found in input symbols table.
Mapping to null...
mei2you311.1864 m ei2 iou3
' not found in input symbols table.
Mapping to null...
mei3wen217.0795 m ei3 ue2 n
' not found in input symbols table.
Mapping to null...
mei4li4 12.8994 m ei4 l i4
' not found in input symbols table.
Mapping to null...
mian3sho15.8597 m ia3 n sh ou4
' not found in input symbols table.
Mapping to null...
nong2hu412.7265 n o2 ng h u4
' not found in input symbols table.
Mapping to null...
po3ju4  16.4514 p o3 j v4
' not found in input symbols table.
Mapping to null...
qi1bai3 11.4689 q i1 b ai3
' not found in input symbols table.
Mapping to null...
qi2     8.97983 q i2
' not found in input symbols table.
Mapping to null...
qi3lai2 11.8612 q i3 l ai2
' not found in input symbols table.
Mapping to null...
qi4xie4 14.0978 q i4 x ie4
' not found in input symbols table.
Mapping to null...
qian2wan11.3375 q ia2 n ua3 ng
' not found in input symbols table.
Mapping to null...
que4zhen17.6488 q ve4 zh e3 n
' not found in input symbols table.
Mapping to null...
ren2gong31.9425ar e2 n g o1 ng l iu2 ch a3 n
' not found in input symbols table.
Mapping to null...
san4wen210.5971 s a4 n ue2 n
' not found in input symbols table.
Mapping to null...
shang4  9.27212 sh a4 ng
' not found in input symbols table.
Mapping to null...
shi2    9.49063 sh ii2
' not found in input symbols table.
Mapping to null...
shi4    9.42106 sh ii4
' not found in input symbols table.
Mapping to null...
shou3zhu11.2987 sh ou3 zh u2
' not found in input symbols table.
Mapping to null...
shui2   12.9392 sh uei2
' not found in input symbols table.
Mapping to null...
si4bai3 11.4928 s ii4 b ai3
' not found in input symbols table.
Mapping to null...
ti3yu4  10.1303 t i3 v4
' not found in input symbols table.
Mapping to null...
ti3yu4yo18.1349 t i3 v4 io4 ng p i3 n
' not found in input symbols table.
Mapping to null...
tie3lan214.2281 t ie3 l a2 n g a1 n
' not found in input symbols table.
Mapping to null...
tou4lu4 11.1447 t ou4 l u4
' not found in input symbols table.
Mapping to null...
wai4jiao13.3861 uai4 j iao1 g ua1 n
' not found in input symbols table.
Mapping to null...
wang2cun17.5714 ua2 ng c ue1 n
' not found in input symbols table.
Mapping to null...
wei2    9.07975 uei2
' not found in input symbols table.
Mapping to null...
wen2cai312.0393 ue2 n c ai3
' not found in input symbols table.
Mapping to null...
wen2ti3 11.4773 ue2 n t i3
' not found in input symbols table.
Mapping to null...
wu3bai3 11.2292 u3 b ai3
' not found in input symbols table.
Mapping to null...
wu3shi2d18.4721 u3 sh ii2 d uo1
' not found in input symbols table.
Mapping to null...
wu3zhuan9.91891 u3 zh ua1 ng
' not found in input symbols table.
Mapping to null...
xiang4  9.19517 x ia4 ng
' not found in input symbols table.
Mapping to null...
xiao3   9.8131  x iao3
' not found in input symbols table.
Mapping to null...
xu1     9.1783  x v1
' not found in input symbols table.
Mapping to null...
ye3     9.23774 ie3
' not found in input symbols table.
Mapping to null...
yi1     9.59779 i1
' not found in input symbols table.
Mapping to null...
yi1tou2 12.2894 i1 t ou2
' not found in input symbols table.
Mapping to null...
yi3     9.51876 i3
' not found in input symbols table.
Mapping to null...
yi4jing411.581  i4 j i4 ng
' not found in input symbols table.
Mapping to null...
yin1    8.95504 i1 n
' not found in input symbols table.
Mapping to null...
yin1zi3 12.9309 i1 n z ii3
' not found in input symbols table.
Mapping to null...
ying4you34.1571ui4 ng iou3 j i3 n iou3
' not found in input symbols table.
Mapping to null...
yong3you11.5361 io3 ng iou3
' not found in input symbols table.
Mapping to null...
yong4   9.33563 io4 ng
' not found in input symbols table.
Mapping to null...
you2yong10.6349 iou2 io3 ng
' not found in input symbols table.
Mapping to null...
you2yu2 13.328  iou2 v2
' not found in input symbols table.
Mapping to null...
you3    9.49451 iou3
' not found in input symbols table.
Mapping to null...
you4    9.13757 iou4
' not found in input symbols table.
Mapping to null...
yu3     9.00152 v3
' not found in input symbols table.
Mapping to null...
yu3yan2 10.5345 v3 ia2 n
' not found in input symbols table.
Mapping to null...
yuan2cun16.2314 va2 n c ue1 n
' not found in input symbols table.
Mapping to null...
yun4dong8.46641 v4 n d o4 ng
' not found in input symbols table.
Mapping to null...
yun4dong13.3096 v4 n d o4 ng va2 n
' not found in input symbols table.
Mapping to null...
yun4fu4 15.6802 v4 n f u4
' not found in input symbols table.
Mapping to null...
zai4    9.3089  z ai4
' not found in input symbols table.
Mapping to null...
zao3yun414.3013 z ao3 v4 n
' not found in input symbols table.
Mapping to null...
zhan4gan12.803  zh a4 n g a3 ng
' not found in input symbols table.
Mapping to null...
zhang1  9.07615 zh a1 ng
' not found in input symbols table.
Mapping to null...
zhe4wei412.1745 zh e4 uei4
' not found in input symbols table.
Mapping to null...
zhi1    9.89655 zh ii1
' not found in input symbols table.
Mapping to null...
zhi1ku3 15.9076 zh ii1 k u3
' not found in input symbols table.
Mapping to null...
zhi4    9.3225  zh ii4
' not found in input symbols table.
Mapping to null...
zhong3  9.83903 zh o3 ng
' not found in input symbols table.
Mapping to null...
zuo4    10.1253 z uo4
have any body know how to resovlute this error ?i will so greatfull to you .

**Comment by AdolfVonKleist** [comment]
Sorry, this means the apostrophe was not included in your input training dictionary.

**Comment by DanielSWolf** [comment]
I'm having the same problem. The thing is: I'm just following the tutorial in the README, and the training dictionary (CMUdict) *does* contain words with apostrophes:

```text
'bout	B AW1 T
'cause	K AH0 Z
'course	K AO1 R S
...
aaron	EH1 R AH0 N
aaron's	EH1 R AH0 N Z
...
```

What's more, the word list doesn't contain a single word with an apostrophe:

```text
Symbol: '
' not found in input symbols table.
Mapping to null...
Symbol: '
' not found in input symbols table.
Mapping to null...
test
	0.80	T EH1 S T
test
	0.16	T EH2 S T
```

So I'm not sure what the warning is telling me.

I'm using the latest Docker image.
