### ISSUE TITLE
phonetisaurus-g2pfst result always empty

### ISSUE THREAD

**Issue by Holzhaus** [AdolfVonKleist/Phonetisaurus#5]
The result from `phonetisaurus-g2pfst` seems to be always empty.

```
$ bin/phonetisaurus-g2pfst --model=/usr/share/phonetisaurus/scripts/g014b2b/g014b2b.fst --word=HELLO
GitRevision: 317a17

$ bin/phonetisaurus-g2pfst --model=/usr/share/phonetisaurus/scripts/g014b2b/g014b2b.fst --word=TEST 
GitRevision: 317a17

```

I looks like [`path_filter.ordered_paths.size()` in `PhonetisaurusScript.h`](https://github.com/AdolfVonKleist/Phonetisaurus/blob/master/src/include/PhonetisaurusScript.h#L149) is always `0`.

**Comment by alexnanchen** [comment]
Same problem with revision: 6e5329-dirty.

Switching to phonetisaurus-g2p (older revision) and using the fst built with revision 6e5329 do output pronunciations.

Using openfst-1.4.1.

**Comment by AdolfVonKleist** [comment]
I believe this should be resolved in the current version of master tied to 1.6.1.  However you would need to rebuild/retrain your models.
