### ISSUE TITLE
training data format

### ISSUE THREAD

**Issue by yondu22** [AdolfVonKleist/Phonetisaurus#50]
is it
word[space]phone[space]phone[space]phone
or 
word[tab]phone[space]phone[space]phone

**Comment by jpetso** [comment]
It's the tab character. However, `phonetisaurus-align` also has an option to change the default for a particular file you train on:

```
  --delim: type = string, default = "   " (<- looks like a bunch of spaces here, but is actually tab)
  Delimiter separating entry one and entry two in the input file.
```

**Comment by yondu22** [comment]
thank you
