### ISSUE TITLE
forcing exact dictionary lookup

### ISSUE THREAD

**Issue by yondu22** [AdolfVonKleist/Phonetisaurus#51]
I have trained with the dictionary, but since it learns to generalize it gets some words that are in the training data wrong for example "the", "to", letters of the alphabet. Is there a way to force if the word is from the training to match it completely? and only generalize for new unseen wodds

**Comment by AdolfVonKleist** [comment]
Yes it makes errors like these.  You will get a better general result [and quicker] if you use it in combination with your reference lexicon.  

There is a small example g2p servlet that shows a simple integration for this:

* https://github.com/AdolfVonKleist/Phonetisaurus/tree/openfst173/python/script

there are also some better alternatives to this out there these days.  I have a transformer-based solution that will be released here before end of year.  I'll continue to fix bugs here, but 'the future is coming' and this is getting pretty dated.

**Comment by yondu22** [comment]
This is great for performance, accuracy seems good enough, and the question is how much more ram, cpu, gpu you need to just increase accuracy a little bit by using neural method

**Comment by jpetso** [comment]
@AdolfVonKleist: For the transformer-based solution you mentioned, did you mean end of year 2019 or 2020? Or academic year? Where would I subscribe to make sure I don't miss this upcoming release?
