### ISSUE TITLE
Syntax error: phonetisaurus-apply

### ISSUE THREAD

**Issue by Ayushi113** [AdolfVonKleist/Phonetisaurus#52]
Hi all,
I'm installing Phonetisaurus, and I am getting this error when running phonetisaurus-apply. 
`phonetisaurus-apply --model train/model.fst --word_list test.wlist`
File "/usr/local/bin/phonetisaurus-apply", line 68
    word, pron = re.split (ur"\t", line, 1)
                                ^
SyntaxError: invalid syntax

I'm on Ubuntu 16.04 and Python 3.5.2. I've followed all the steps for installation up until here, and all seems to work well. 
Thank you so much in advance!!

**Comment by AdolfVonKleist** [comment]
The 'u' flag there is an artifact from python 2.7.  It is not legal as a string modifier in the `re` module in 3.x, that is why it is complaining.

**Comment by Ayushi113** [comment]
Thanks a lot for your response! I've removed that but then there's quite a few changes to be made to the code. Would that be the recommended way, or can I do something else with the installation?
Thanks so much, once again!

**Comment by vesis84** [comment]
I have the same problem, when running in python3.

I guess, py2py3 compatible solution would be to use: 
```python
from __future__ import unicode_literals
```
and replace all ur"..." by r"..."

**Comment by Ayushi113** [comment]
Hi.. I created a virtualenv where I installed phonetisaurus again, and restricted the use of python to python2. That is working for now.

**Comment by AdolfVonKleist** [comment]
I guess it is time to finalize a python3 transition, and maybe forget entirely about two.  I don't think it makes sense to track both.
