### ISSUE TITLE
Time for a release?

### ISSUE THREAD

**Issue by Mic92** [AdolfVonKleist/Phonetisaurus#61]
I am trying to add phonetisaurus to [nixpkgs](https://github.com/NixOS/nixpkgs/) and it would make a better impression if there would be some sort of releases.

**Comment by Mic92** [comment]
So I assume the answer is no?

**Comment by AdolfVonKleist** [comment]
Hi I would like to help support you in this, but we would need a low-effort strategy.  Such a strategy could also dove-tail with the dockerization that @danijel3 has recently contributed.  What you need from my side to support this effort?

**Comment by Mic92** [comment]
We would just need tagged releases every once in a while. I.e. starting with 1.0.0
We have than automatic bots looking for these tags an proposing updates in nixpkgs.

**Comment by Mic92** [comment]
This could be as easy as doing:

```console
$ git tag 1.0.0
$ git push --tags
```

**Comment by AdolfVonKleist** [comment]
Ok I gave it a try:
-  https://github.com/AdolfVonKleist/Phonetisaurus/releases/tag/0.9.1

**Comment by Mic92** [comment]
Thanks!
