### ISSUE TITLE
Updated OSX Install Instructions

### ISSUE THREAD

**Issue by AlJohri** [AdolfVonKleist/Phonetisaurus#8]
It seems like because of the way the `src/configure` is written there is currently a **hard dependency on openfst 1.4.1**. The checking of dylib is broken because it seems like the directory structure changed in openfst 1.5 from `$lib/fst/myfile.dylib` to  `$lib/myfile.dylib`. After fixing this, other errors persisted with the newest openfst so I just downgraded.

Please see my edited openfst formula here: https://gist.github.com/AlJohri/315251f54653a3c3ffe3ccb41b074848

**Complete Installation Instructions**

```
git clone https://github.com/AdolfVonKleist/Phonetisaurus.git
cd src
brew install https://gist.githubusercontent.com/AlJohri/315251f54653a3c3ffe3ccb41b074848/raw/fe64404ae714abea0d88ee1b9e2f676b81f81296/openfst.rb
./configure --with-openfst-libs=/usr/local/opt/openfst/lib --with-openfst-includes=/usr/local/opt/openfst/include
make -j 2 all
```

**Comment by DanielAsher** [comment]
@AlJohri thanks so much for this!

👍 👍 👍

**Comment by AdolfVonKleist** [comment]
@AlJohri thanks!  There are some breaking changes across 1.4x ~ 1.6x in openfst, I'd like to get a flexible solution to this, but at the moment I have only separate branches for a couple of the major versions.

**Comment by shaynemei** [comment]
I am getting this error when running the last line following this installation guide on OSX Catalina.

`In file included from src/bin/phonetisaurus-align.cc:35:
./src/include/PhonetisaurusRex.h:247:3: error: no template named 'ShortestPathCompare' in namespace
      'fst::internal'; did you mean simply 'ShortestPathCompare'?`
